[project]
name = "spatiotemporal-env"
version = "0.1.0"
description = "Enviroment for graph-based spatiotemporal modeling"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
  "torch>=2.5,<2.6",
  "torchvision>=0.20,<0.21",
  "torchaudio>=2.5,<2.6",
  "torch-geometric>=2.7.0",
  "pyg-lib>=0.4.0; sys_platform == 'linux'",
  "torch-scatter>=2.1.2",
  "torch-sparse>=0.6.18",
  "torch-cluster>=1.6.3",
  "torch-spatiotemporal[experiment]",
  "wandb>=0.25.0",
  "numpy<2",
  "pandas<3",
  "ipykernel",
  "pip",
  "peakweather",
  "matplotlib>=3.10.8",
  "tensorboard>=2.20.0",
  "setuptools<82",
]

[tool.uv]
environments = [
  "sys_platform == 'darwin'",
  "sys_platform == 'linux'",
]

[tool.uv.sources]
torch-spatiotemporal = { git = "https://github.com/TorchSpatiotemporal/tsl", rev = "dev" }
torch = [
  { index = "pytorch-cu121", marker = "sys_platform == 'linux'" }
]
torchvision = [
  { index = "pytorch-cu121", marker = "sys_platform == 'linux'" }
]
torchaudio = [
  { index = "pytorch-cu121", marker = "sys_platform == 'linux'" }
]

pyg-lib = [
  { index = "pyg-cu121", marker = "sys_platform == 'linux'" }
]
torch-scatter = [
  { index = "pyg-cu121", marker = "sys_platform == 'linux'" },
  { index = "pyg-cpu", marker = "sys_platform == 'darwin'" }
]
torch-sparse = [
  { index = "pyg-cu121", marker = "sys_platform == 'linux'" },
  { index = "pyg-cpu", marker = "sys_platform == 'darwin'" }
]
torch-cluster = [
  { index = "pyg-cu121", marker = "sys_platform == 'linux'" },
  { index = "pyg-cpu", marker = "sys_platform == 'darwin'" }
]
peakweather = { git = "https://github.com/MeteoSwiss/PeakWeather"}

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[[tool.uv.index]]
name = "pyg-cu121"
url = "https://data.pyg.org/whl/torch-2.5.0+cu121.html"
format = "flat"
explicit = true

[[tool.uv.index]]
name = "pyg-cpu"
url = "https://data.pyg.org/whl/torch-2.5.0+cpu.html"
format = "flat"
explicit = true
